import { Inter } from 'next/font/google';
import "./globals.css";

export const inter = Inter({
  subsets: ['latin'],
  style: ['normal'],
  weight: ['500']
})

export const metadata = {
  title: "None",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="bg-zinc-900 text-zinc-50 scrollbar-thin scrollbar-track-zinc-800 scrollbar-thumb-zinc-500">
      <body
        className={`${inter.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
